In [1]:
# import dependencies
import pandas as pd

In [2]:
# read csv file
file = "Datasets\cdc_npao.csv"
npao_original = pd.read_csv(file, encoding="utf-8")
npao_original.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD

In [12]:
# check if all states represented
print("*" * 30 + 'List of States' + "*" *30)
print("*" * 74)
print(npao_original["LocationDesc"].unique())
print("*" * 74)
print(f'Number of states represented in dataset: {len(npao_original["LocationDesc"].unique())}')

******************************List of States******************************
**************************************************************************
['Alabama' 'National' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Connecticut' 'Colorado' 'Delaware' 'Florida' 'District of Columbia'
 'Georgia' 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'West Virginia' 'Washington' 'Wisconsin' 'Wyoming']
**************************************************************************
Number of states represented in dataset: 54

In [13]:
# get information about variables types and values available
npao_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48772 entries, 0 to 48771
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   YearStart                   48772 non-null  int64
 1   YearEnd                     48772 non-null  int64
 2   LocationAbbr                48772 non-null  object
 3   LocationDesc                48772 non-null  object
 4   Datasource                  48772 non-null  object
 5   Class                       48772 non-null  object
 6   Topic                       48772 non-null  object
 7   Question                    48772 non-null  object
 8   Data_Value_Unit             0 non-null      float64
 9   Data_Value_Type             48772 non-null  object
 10  Data_Value                  44169 non-null  float64
 11  Data_Value_Alt              44169 non-null  float64
 12  Data_Value_Footnote_Symbol  4603 non-null   object
 13  Data_Value_Footnote         4603 non-null   object
 14  Low_Confidence_Limit        44169 non-null  float64
 15  High_Confidence_Limit       44169 non-null  float64
 16  Sample_Size                 44169 non-null  float64
 17  Total                       1742 non-null   object
 18  Age(years)                  10448 non-null  object
 19  Education                   6968 non-null   object
 20  Gender                      3484 non-null   object
 21  Income                      12194 non-null  object
 22  Race/Ethnicity              13936 non-null  object
 23  GeoLocation                 47848 non-null  object
 24  ClassID                     48772 non-null  object
 25  TopicID                     48772 non-null  object
 26  QuestionID                  48772 non-null  object
 27  DataValueTypeID             48772 non-null  object
 28  LocationID                  48772 non-null  int64
 29  StratificationCategory1     48772 non-null  object
 30  Stratification1             48772 non-null  object
 31  StratificationCategoryId1   48772 non-null  object
 32  StratificationID1           48772 non-null  object
dtypes: float64(6), int64(3), object(24)
memory usage: 12.3+ MB

In [27]:
# check values of variables
print("Data_Value_Type")
print("-" * 30)
print(npao_original["Data_Value_Type"].value_counts())
print("*" * 74)
print("Datasource")
print("-" * 30)
print(npao_original["Datasource"].value_counts())
print("*" * 74)
print("Class")
print("-" * 30)
print(npao_original["Class"].value_counts())
print("*" * 74)
print("Topic")
print("-" * 30)
print(npao_original["Topic"].value_counts())
print("*" * 74)

Data_Value_Type
------------------------------
Value    48772
Name: Data_Value_Type, dtype: int64
**************************************************************************
Datasource
------------------------------
Behavioral Risk Factor Surveillance System    48772
Name: Datasource, dtype: int64
**************************************************************************
Class
------------------------------
Physical Activity          25088
Obesity / Weight Status    14840
Fruits and Vegetables       8844
Name: Class, dtype: int64
**************************************************************************
Topic
------------------------------
Physical Activity - Behavior        25088
Obesity / Weight Status             14840
Fruits and Vegetables - Behavior     8844
Name: Topic, dtype: int64
**************************************************************************

In [29]:
# check values of variables
print("Data_Value_Alt")
print("-" * 30)
print(npao_original["Data_Value_Alt"].value_counts())
print("*" * 74)
print("Data_Value_Footnote_Symbol")
print("-" * 30)
print(npao_original["Data_Value_Footnote_Symbol"].value_counts())
print("*" * 74)
print('Data_Value_Footnote')
print("-" * 30)
print(npao_original["Data_Value_Footnote"].value_counts())
print("*" * 74)
print("Question")
print("-" * 30)
print(npao_original["Question"].value_counts())
print("*" * 74)

Data_Value_Alt
------------------------------
29.6    210
30.2    210
32.7    203
35.9    197
29.4    196
       ...
62.9      1
0.9       1
71.7      1
68.0      1
6.0       1
Name: Data_Value_Alt, Length: 667, dtype: int64
**************************************************************************
Data_Value_Footnote_Symbol
------------------------------
~    4603
Name: Data_Value_Footnote_Symbol, dtype: int64
**************************************************************************
Data_Value_Footnote
------------------------------
Data not available because sample size is insufficient.                                                                                                   4181
Data not available because sample size is insufficient.  If data only missing for the confidence interval, the confidence interval was not calculated.     422
Name: Data_Value_Footnote, dtype: int64
**************************************************************************
Question
------------------------------
Percent of adults aged 18 years and older who have obesity                                                                                                                                                                                               7420
Percent of adults aged 18 years and older who have an overweight classification                                                                                                                                                                          7420
Percent of adults who engage in no leisure-time physical activity                                                                                                                                                                                        7392
Percent of adults who engage in muscle-strengthening activities on 2 or more days a week                                                                                                                                                                 4424
Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)                                                     4424
Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)                                                    4424
Percent of adults who report consuming vegetables less than one time daily                                                                                                                                                                               4424
Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week    4424
Percent of adults who report consuming fruit less than one time daily                                                                                                                                                                                    4420
Name: Question, dtype: int64
**************************************************************************

In [14]:
# check list of column, to reduce columns
npao_original.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

In [30]:
npao_reduced = npao_original[['YearStart', 'LocationDesc', 'GeoLocation', 'Class', 
                              'Question', 'Data_Value', 'Data_Value_Alt', 'Sample_Size']]
npao_reduced.head()

,YearStart,LocationDesc,GeoLocation,Class,Question,Data_Value,Data_Value_Alt,Sample_Size
0,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.0,32.0,7304.0
1,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.3,32.3,2581.0
2,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,31.8,31.8,4723.0
3,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,33.6,33.6,1153.0
4,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.8,32.8,2402.0

In [35]:
# checking if Data value and data value alt are the same throughout
npao_reduced["value_same_alt"] = npao_reduced["Data_Value"] == npao_reduced["Data_Value_Alt"]  
npao_reduced["value_same_alt"].value_counts()

C:\Users\liats\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

True     44169
False     4603
Name: value_same_alt, dtype: int64

In [39]:
npao_reduced.loc[npao_reduced["value_same_alt"] == False, :].head()

,YearStart,LocationDesc,GeoLocation,Class,Question,Data_Value,Data_Value_Alt,Sample_Size,value_same_alt
23,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,NaN,False
24,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,NaN,False
27,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,NaN,False
51,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,NaN,False
52,2011,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,NaN,False

In [40]:
npao_reduced = npao_reduced.dropna(how='any')
npao_reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43245 entries, 0 to 48771
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   YearStart       43245 non-null  int64
 1   LocationDesc    43245 non-null  object
 2   GeoLocation     43245 non-null  object
 3   Class           43245 non-null  object
 4   Question        43245 non-null  object
 5   Data_Value      43245 non-null  float64
 6   Data_Value_Alt  43245 non-null  float64
 7   Sample_Size     43245 non-null  float64
 8   value_same_alt  43245 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(4)
memory usage: 3.0+ MB

In [43]:
# removing columns that are not needed
npao_reduced = npao_reduced[['LocationDesc', 'GeoLocation', 'Class', 'Question', 'Data_Value', 'Sample_Size']]
npao_reduced.tail()

,LocationDesc,GeoLocation,Class,Question,Data_Value,Sample_Size
48760,Puerto Rico,"(18.220833, -66.590149)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,39.5,186.0
48761,Puerto Rico,"(18.220833, -66.590149)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,40.5,422.0
48762,Puerto Rico,"(18.220833, -66.590149)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,43.7,317.0
48763,Puerto Rico,"(18.220833, -66.590149)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,37.5,5154.0
48771,Puerto Rico,"(18.220833, -66.590149)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,37.6,5104.0

In [45]:
# need to create a new column- the product of sample size times data value (to later calculate weighted average)
npao_reduced["ValueXSample"] = npao_reduced["Data_Value"] * npao_reduced["Sample_Size"]
npao_reduced.head()

,LocationDesc,GeoLocation,Class,Question,Data_Value,Sample_Size,ValueXSample
0,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.0,7304.0,233728.0
1,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.3,2581.0,83366.3
2,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,31.8,4723.0,150191.4
3,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,33.6,1153.0,38740.8
4,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.8,2402.0,78785.6

In [62]:
# reformatting the data frame
npao = npao_reduced.groupby(["LocationDesc", "GeoLocation", "Class", "Question"])["ValueXSample", "Sample_Size"].sum()
npao

C:\Users\liats\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

                                                                                                                                  ValueXSample  \
LocationDesc GeoLocation                              Class                   Question
Alabama      (32.84057112200048, -86.63186076199969)  Fruits and Vegetables   Percent of adults who report consuming fruit le...     5311147.2
                                                                              Percent of adults who report consuming vegetabl...     3051087.1
                                                      Obesity / Weight Status Percent of adults aged 18 years and older who h...     7766780.1
                                                                              Percent of adults aged 18 years and older who h...     7546136.6
                                                      Physical Activity       Percent of adults who achieve at least 150 minu...     5286812.9
...                                                                                                                                        ...
Wyoming      (43.23554134300048, -108.10983035299967) Physical Activity       Percent of adults who achieve at least 150 minu...     5474756.7
                                                                              Percent of adults who achieve at least 150 minu...     2128092.1
                                                                              Percent of adults who achieve at least 300 minu...     3533692.7
                                                                              Percent of adults who engage in muscle-strength...     3056632.5
                                                                              Percent of adults who engage in no leisure-time...     4372689.5

                                                                                                                                  Sample_Size
LocationDesc GeoLocation                              Class                   Question
Alabama      (32.84057112200048, -86.63186076199969)  Fruits and Vegetables   Percent of adults who report consuming fruit le...     116465.0
                                                                              Percent of adults who report consuming vegetabl...     119184.0
                                                      Obesity / Weight Status Percent of adults aged 18 years and older who h...     225761.0
                                                                              Percent of adults aged 18 years and older who h...     225798.0
                                                      Physical Activity       Percent of adults who achieve at least 150 minu...     120273.0
...                                                                                                                                       ...
Wyoming      (43.23554134300048, -108.10983035299967) Physical Activity       Percent of adults who achieve at least 150 minu...     101182.0
                                                                              Percent of adults who achieve at least 150 minu...     100136.0
                                                                              Percent of adults who achieve at least 300 minu...     100255.0
                                                                              Percent of adults who engage in muscle-strength...     103908.0
                                                                              Percent of adults who engage in no leisure-time...     180685.0

[477 rows x 2 columns]

In [63]:
# converting the groupby object to a dataframe
npao = npao.reset_index()
npao

,LocationDesc,GeoLocation,Class,Question,ValueXSample,Sample_Size
0,Alabama,"(32.84057112200048, -86.63186076199969)",Fruits and Vegetables,Percent of adults who report consuming fruit l...,5311147.2,116465.0
1,Alabama,"(32.84057112200048, -86.63186076199969)",Fruits and Vegetables,Percent of adults who report consuming vegetab...,3051087.1,119184.0
2,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,7766780.1,225761.0
3,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,7546136.6,225798.0
4,Alabama,"(32.84057112200048, -86.63186076199969)",Physical Activity,Percent of adults who achieve at least 150 min...,5286812.9,120273.0
...,...,...,...,...,...,...
472,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 150 min...,5474756.7,101182.0
473,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 150 min...,2128092.1,100136.0
474,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 300 min...,3533692.7,100255.0
475,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who engage in muscle-strengt...,3056632.5,103908.0
476,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who engage in no leisure-tim...,4372689.5,180685.0

In [64]:
# calculating a column with the weighted average rate per question
npao["Average %"] = npao["ValueXSample"] / npao["Sample_Size"]
npao

,LocationDesc,GeoLocation,Class,Question,ValueXSample,Sample_Size,Average %
0,Alabama,"(32.84057112200048, -86.63186076199969)",Fruits and Vegetables,Percent of adults who report consuming fruit l...,5311147.2,116465.0,45.602947
1,Alabama,"(32.84057112200048, -86.63186076199969)",Fruits and Vegetables,Percent of adults who report consuming vegetab...,3051087.1,119184.0,25.599805
2,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,7766780.1,225761.0,34.402665
3,Alabama,"(32.84057112200048, -86.63186076199969)",Obesity / Weight Status,Percent of adults aged 18 years and older who ...,7546136.6,225798.0,33.419856
4,Alabama,"(32.84057112200048, -86.63186076199969)",Physical Activity,Percent of adults who achieve at least 150 min...,5286812.9,120273.0,43.956773
...,...,...,...,...,...,...,...
472,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 150 min...,5474756.7,101182.0,54.108010
473,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 150 min...,2128092.1,100136.0,21.252018
474,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who achieve at least 300 min...,3533692.7,100255.0,35.247047
475,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who engage in muscle-strengt...,3056632.5,103908.0,29.416720
476,Wyoming,"(43.23554134300048, -108.10983035299967)",Physical Activity,Percent of adults who engage in no leisure-tim...,4372689.5,180685.0,24.200623

In [65]:
# need to recreate the data frame such that each question would appear in a different column 
#and will have it's corresponding average %

# first, get rid of columns that are not needed
npao = npao[["LocationDesc", "GeoLocation", "Question", "Average %"]]
npao

,LocationDesc,GeoLocation,Question,Average %
0,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults who report consuming fruit l...,45.602947
1,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults who report consuming vegetab...,25.599805
2,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults aged 18 years and older who ...,34.402665
3,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults aged 18 years and older who ...,33.419856
4,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults who achieve at least 150 min...,43.956773
...,...,...,...,...
472,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who achieve at least 150 min...,54.108010
473,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who achieve at least 150 min...,21.252018
474,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who achieve at least 300 min...,35.247047
475,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who engage in muscle-strengt...,29.416720
476,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who engage in no leisure-tim...,24.200623

In [68]:
# start with obesity
obesity_df = npao.loc[npao["Question"] == 'Percent of adults aged 18 years and older who have obesity', :].reset_index(drop=True)
obesity_df

,LocationDesc,GeoLocation,Question,Average %
0,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults aged 18 years and older who ...,33.419856
1,Alaska,"(64.84507995700051, -147.72205903599973)",Percent of adults aged 18 years and older who ...,28.337146
2,Arizona,"(34.865970280000454, -111.76381127699972)",Percent of adults aged 18 years and older who ...,27.033482
3,Arkansas,"(34.74865012400045, -92.27449074299966)",Percent of adults aged 18 years and older who ...,33.932269
4,California,"(37.63864012300047, -120.99999953799971)",Percent of adults aged 18 years and older who ...,24.056118
5,Colorado,"(38.843840757000464, -106.13361092099967)",Percent of adults aged 18 years and older who ...,20.719864
6,Connecticut,"(41.56266102000046, -72.64984095199964)",Percent of adults aged 18 years and older who ...,25.270320
7,Delaware,"(39.008830667000495, -75.57774116799965)",Percent of adults aged 18 years and older who ...,29.443461
8,District of Columbia,"(38.89037138500049, -77.03196112699965)",Percent of adults aged 18 years and older who ...,22.511001
9,Florida,"(28.932040377000476, -81.92896053899966)",Percent of adults aged 18 years and older who ...,26.199897
10,Georgia,"(32.83968109300048, -83.62758034599966)",Percent of adults aged 18 years and older who ...,29.556174
11,Guam,"(13.444304, 144.793731)",Percent of adults aged 18 years and older who ...,29.022690
12,Hawaii,"(21.304850435000446, -157.85774940299973)",Percent of adults aged 18 years and older who ...,22.179215
13,Idaho,"(43.682630005000476, -114.3637300419997)",Percent of adults aged 18 years and older who ...,28.148357
14,Illinois,"(40.48501028300046, -88.99771017799969)",Percent of adults aged 18 years and older who ...,28.978075
15,Indiana,"(39.766910452000445, -86.14996019399968)",Percent of adults aged 18 years and older who ...,31.773124
16,Iowa,"(42.46940091300047, -93.81649055599968)",Percent of adults aged 18 years and older who ...,30.854645
17,Kansas,"(38.34774030000045, -98.20078122699965)",Percent of adults aged 18 years and older who ...,31.062287
18,Kentucky,"(37.645970271000465, -84.77497104799966)",Percent of adults aged 18 years and older who ...,32.263497
19,Louisiana,"(31.31266064400046, -92.44568007099969)",Percent of adults aged 18 years and older who ...,34.365733
20,Maine,"(45.254228894000505, -68.98503133599962)",Percent of adults aged 18 years and older who ...,28.514265
21,Maryland,"(39.29058096400047, -76.60926011099963)",Percent of adults aged 18 years and older who ...,28.576942
22,Massachusetts,"(42.27687047000046, -72.08269067499964)",Percent of adults aged 18 years and older who ...,23.393157
23,Michigan,"(44.6613195430005, -84.71439026999968)",Percent of adults aged 18 years and older who ...,31.207155
24,Minnesota,"(46.35564873600049, -94.79420050299967)",Percent of adults aged 18 years and older who ...,26.250866
25,Mississippi,"(32.745510099000455, -89.53803082499968)",Percent of adults aged 18 years and older who ...,34.996405
26,Missouri,"(38.635790776000476, -92.56630005299968)",Percent of adults aged 18 years and older who ...,30.696429
27,Montana,"(47.06652897200047, -109.42442064499971)",Percent of adults aged 18 years and older who ...,24.802586
28,Nebraska,"(41.6410409880005, -99.36572062299967)",Percent of adults aged 18 years and older who ...,29.710778
29,Nevada,"(39.493240390000494, -117.07184056399967)",Percent of adults aged 18 years and older who ...,25.861857
30,New Hampshire,"(43.65595011300047, -71.50036091999965)",Percent of adults aged 18 years and older who ...,26.891074
31,New Jersey,"(40.13057004800049, -74.27369128799967)",Percent of adults aged 18 years and older who ...,25.447574
32,New Mexico,"(34.52088095200048, -106.24058098499967)",Percent of adults aged 18 years and older who ...,26.919168
33,New York,"(42.82700103200045, -75.54397042699964)",Percent of adults aged 18 years and older who ...,25.100855
34,North Carolina,"(35.466220975000454, -79.15925046299964)",Percent of adults aged 18 years and older who ...,29.497386
35,North Dakota,"(47.47531977900047, -100.11842104899966)",Percent of adults aged 18 years and older who ...,30.679661
36,Ohio,"(40.06021014100048, -82.40426005599966)",Percent of adults aged 18 years and older who ...,30.614958
37,Oklahoma,"(35.47203135600046, -97.52107021399968)",Percent of adults aged 18 years and older who ...,32.426650
38,Oregon,"(44.56744942400047, -120.15503132599969)",Percent of adults aged 18 years and older who ...,27.455250
39,Pennsylvania,"(40.79373015200048, -77.86070029399963)",Percent of adults aged 18 years and older who ...,29.527338
40,Puerto Rico,"(18.220833, -66.590149)",Percent of adults aged 18 years and older who ...,28.511018
41,Rhode Island,"(41.70828019300046, -71.52247031399963)",Percent of adults aged 18 years and older who ...,26.250716
42,South Carolina,"(33.998821303000454, -81.04537120699968)",Percent of adults aged 18 years and older who ...,31.566059
43,South Dakota,"(44.353130053000484, -100.3735306369997)",Percent of adults aged 18 years and older who ...,29.380326
44,Tennessee,"(35.68094058000048, -85.77449091399967)",Percent of adults aged 18 years and older who ...,31.809394
45,Texas,"(31.827240407000488, -99.42677020599967)",Percent of adults aged 18 years and older who ...,30.892873
46,Utah,"(39.360700171000474, -111.58713063499971)",Percent of adults aged 18 years and older who ...,24.841872
47,Vermont,"(43.62538123900049, -72.51764079099962)",Percent of adults aged 18 years and older who ...,24.784377
48,Virginia,"(37.54268067400045, -78.45789046299967)",Percent of adults aged 18 years and older who ...,28.383090
49,Washington,"(47.52227862900048, -120.47001078999972)",Percent of adults aged 18 years and older who ...,26.881017
50,West Virginia,"(38.66551020200046, -80.71264013499967)",Percent of adults aged 18 years and older who ...,34.615289
51,Wisconsin,"(44.39319117400049, -89.81637074199966)",Percent of adults aged 18 years and older who ...,30.126659
52,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults aged 18 years and older who ...,26.937223

In [69]:
# grab the columns as arrays
locations = obesity_df["LocationDesc"]
geo = obesity_df["GeoLocation"]
obesity = obesity_df["Average %"]

In [74]:
# getting all other vars
overweight_df = npao.loc[npao["Question"] == 'Percent of adults aged 18 years and older who have an overweight classification', :].reset_index(drop=True)
inactivity_df = npao.loc[npao["Question"] == 'Percent of adults who engage in no leisure-time physical activity', :].reset_index(drop=True)
strength_df = npao.loc[npao["Question"] == 'Percent of adults who engage in muscle-strengthening activities on 2 or more days a week', :].reset_index(drop=True)                                                                                                                                                                      
conditioning_low_df = npao.loc[npao["Question"] == 'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)', :].reset_index(drop=True)                                                                                                                                                                                     
conditioning_high_df = npao.loc[npao["Question"] == 'Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)', :].reset_index(drop=True)                                                                                                                                                                                      
strength_conditioning_df = npao.loc[npao["Question"] == 'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week', :].reset_index(drop=True)                                                                                                                                                              
no_veggies_df = npao.loc[npao["Question"] == 'Percent of adults who report consuming vegetables less than one time daily', :].reset_index(drop=True)                                                  
no_fruit_df = npao.loc[npao["Question"] == 'Percent of adults who report consuming fruit less than one time daily', :].reset_index(drop=True)                                                   
no_fruit_df

,LocationDesc,GeoLocation,Question,Average %
0,Alabama,"(32.84057112200048, -86.63186076199969)",Percent of adults who report consuming fruit l...,45.602947
1,Alaska,"(64.84507995700051, -147.72205903599973)",Percent of adults who report consuming fruit l...,39.087520
2,Arizona,"(34.865970280000454, -111.76381127699972)",Percent of adults who report consuming fruit l...,38.150600
3,Arkansas,"(34.74865012400045, -92.27449074299966)",Percent of adults who report consuming fruit l...,48.642681
4,California,"(37.63864012300047, -120.99999953799971)",Percent of adults who report consuming fruit l...,31.444280
5,Colorado,"(38.843840757000464, -106.13361092099967)",Percent of adults who report consuming fruit l...,35.076421
6,Connecticut,"(41.56266102000046, -72.64984095199964)",Percent of adults who report consuming fruit l...,33.222450
7,Delaware,"(39.008830667000495, -75.57774116799965)",Percent of adults who report consuming fruit l...,38.813472
8,District of Columbia,"(38.89037138500049, -77.03196112699965)",Percent of adults who report consuming fruit l...,33.236759
9,Florida,"(28.932040377000476, -81.92896053899966)",Percent of adults who report consuming fruit l...,37.473051
10,Georgia,"(32.83968109300048, -83.62758034599966)",Percent of adults who report consuming fruit l...,42.297439
11,Guam,"(13.444304, 144.793731)",Percent of adults who report consuming fruit l...,43.432836
12,Hawaii,"(21.304850435000446, -157.85774940299973)",Percent of adults who report consuming fruit l...,39.265357
13,Idaho,"(43.682630005000476, -114.3637300419997)",Percent of adults who report consuming fruit l...,37.986817
14,Illinois,"(40.48501028300046, -88.99771017799969)",Percent of adults who report consuming fruit l...,36.474000
15,Indiana,"(39.766910452000445, -86.14996019399968)",Percent of adults who report consuming fruit l...,42.221754
16,Iowa,"(42.46940091300047, -93.81649055599968)",Percent of adults who report consuming fruit l...,39.355784
17,Kansas,"(38.34774030000045, -98.20078122699965)",Percent of adults who report consuming fruit l...,41.701174
18,Kentucky,"(37.645970271000465, -84.77497104799966)",Percent of adults who report consuming fruit l...,45.728598
19,Louisiana,"(31.31266064400046, -92.44568007099969)",Percent of adults who report consuming fruit l...,47.148136
20,Maine,"(45.254228894000505, -68.98503133599962)",Percent of adults who report consuming fruit l...,33.267740
21,Maryland,"(39.29058096400047, -76.60926011099963)",Percent of adults who report consuming fruit l...,35.378892
22,Massachusetts,"(42.27687047000046, -72.08269067499964)",Percent of adults who report consuming fruit l...,31.943959
23,Michigan,"(44.6613195430005, -84.71439026999968)",Percent of adults who report consuming fruit l...,37.393701
24,Minnesota,"(46.35564873600049, -94.79420050299967)",Percent of adults who report consuming fruit l...,36.508695
25,Mississippi,"(32.745510099000455, -89.53803082499968)",Percent of adults who report consuming fruit l...,50.075485
26,Missouri,"(38.635790776000476, -92.56630005299968)",Percent of adults who report consuming fruit l...,43.136154
27,Montana,"(47.06652897200047, -109.42442064499971)",Percent of adults who report consuming fruit l...,38.407926
28,Nebraska,"(41.6410409880005, -99.36572062299967)",Percent of adults who report consuming fruit l...,39.805204
29,Nevada,"(39.493240390000494, -117.07184056399967)",Percent of adults who report consuming fruit l...,36.027024
30,New Hampshire,"(43.65595011300047, -71.50036091999965)",Percent of adults who report consuming fruit l...,31.958827
31,New Jersey,"(40.13057004800049, -74.27369128799967)",Percent of adults who report consuming fruit l...,34.348319
32,New Mexico,"(34.52088095200048, -106.24058098499967)",Percent of adults who report consuming fruit l...,39.063084
33,New York,"(42.82700103200045, -75.54397042699964)",Percent of adults who report consuming fruit l...,34.845633
34,North Carolina,"(35.466220975000454, -79.15925046299964)",Percent of adults who report consuming fruit l...,41.495537
35,North Dakota,"(47.47531977900047, -100.11842104899966)",Percent of adults who report consuming fruit l...,39.212627
36,Ohio,"(40.06021014100048, -82.40426005599966)",Percent of adults who report consuming fruit l...,41.102722
37,Oklahoma,"(35.47203135600046, -97.52107021399968)",Percent of adults who report consuming fruit l...,49.875869
38,Oregon,"(44.56744942400047, -120.15503132599969)",Percent of adults who report consuming fruit l...,33.170451
39,Pennsylvania,"(40.79373015200048, -77.86070029399963)",Percent of adults who report consuming fruit l...,36.767482
40,Puerto Rico,"(18.220833, -66.590149)",Percent of adults who report consuming fruit l...,55.253744
41,Rhode Island,"(41.70828019300046, -71.52247031399963)",Percent of adults who report consuming fruit l...,34.374334
42,South Carolina,"(33.998821303000454, -81.04537120699968)",Percent of adults who report consuming fruit l...,44.979959
43,South Dakota,"(44.353130053000484, -100.3735306369997)",Percent of adults who report consuming fruit l...,39.804510
44,Tennessee,"(35.68094058000048, -85.77449091399967)",Percent of adults who report consuming fruit l...,44.953283
45,Texas,"(31.827240407000488, -99.42677020599967)",Percent of adults who report consuming fruit l...,41.079994
46,Utah,"(39.360700171000474, -111.58713063499971)",Percent of adults who report consuming fruit l...,35.629856
47,Vermont,"(43.62538123900049, -72.51764079099962)",Percent of adults who report consuming fruit l...,31.999903
48,Virginia,"(37.54268067400045, -78.45789046299967)",Percent of adults who report consuming fruit l...,38.172417
49,Washington,"(47.52227862900048, -120.47001078999972)",Percent of adults who report consuming fruit l...,35.196608
50,West Virginia,"(38.66551020200046, -80.71264013499967)",Percent of adults who report consuming fruit l...,47.279559
51,Wisconsin,"(44.39319117400049, -89.81637074199966)",Percent of adults who report consuming fruit l...,36.581041
52,Wyoming,"(43.23554134300048, -108.10983035299967)",Percent of adults who report consuming fruit l...,39.319413

In [77]:
# building the new data frame
npao_final = pd.DataFrame({"State": locations, "Long & Lat":geo, "Obesity %": obesity, 
                           "Overweight %": overweight_df["Average %"], 
                           "In-Active %": inactivity_df["Average %"], 
                           "Muscle Strengthening %": strength_df["Average %"], 
                           "Low Aerobics %": conditioning_low_df["Average %"], 
                           "High Aerobics %": conditioning_high_df["Average %"], 
                           "Strength & Conditioning %": strength_conditioning_df["Average %"], 
                           "Low Veggies Consumption %": no_veggies_df["Average %"], 
                           "Low Fruit Consumption %": no_fruit_df["Average %"]})
npao_final.head()

,State,Long & Lat,Obesity %,Overweight %,In-Active %,Muscle Strengthening %,Low Aerobics %,High Aerobics %,Strength & Conditioning %,Low Veggies Consumption %,Low Fruit Consumption %
0,Alabama,"(32.84057112200048, -86.63186076199969)",33.419856,34.402665,30.351719,24.379398,43.956773,25.801610,15.482848,25.599805,45.602947
1,Alaska,"(64.84507995700051, -147.72205903599973)",28.337146,37.627901,20.651719,34.140096,57.327324,37.255386,24.586290,18.776312,39.087520
2,Arizona,"(34.865970280000454, -111.76381127699972)",27.033482,36.211155,22.765078,31.002902,53.824667,34.435845,22.613209,20.743749,38.150600
3,Arkansas,"(34.74865012400045, -92.27449074299966)",33.932269,34.859221,32.900491,22.912310,43.908805,27.368902,14.846760,27.518560,48.642681
4,California,"(37.63864012300047, -120.99999953799971)",24.056118,35.882303,19.668067,32.605964,58.273079,36.688512,23.774697,16.757566,31.444280

In [80]:
npao_final.to_csv("Datasets/npao_final.csv", encoding="utf-8", index=False, header=True)